// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp4ypysRNWPUOa_7c6qornqmzHKWuVNrI',
    appId: '1:750270234587:web:9b09ca1b3c77a51572f1fe',
    messagingSenderId: '750270234587',
    projectId: 'nk-one-chat-app',
    authDomain: 'nk-one-chat-app.firebaseapp.com',
    storageBucket: 'nk-one-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpCwJFNbsQUgc-WjgURb7SNsXP9IbFvlw',
    appId: '1:750270234587:android:5c8c32750d860e8572f1fe',
    messagingSenderId: '750270234587',
    projectId: 'nk-one-chat-app',
    storageBucket: 'nk-one-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaaOrH9yH64gd2H8Z-ZJWFSV1SThbZA-A',
    appId: '1:750270234587:ios:686206231878fc0272f1fe',
    messagingSenderId: '750270234587',
    projectId: 'nk-one-chat-app',
    storageBucket: 'nk-one-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.oneChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaaOrH9yH64gd2H8Z-ZJWFSV1SThbZA-A',
    appId: '1:750270234587:ios:686206231878fc0272f1fe',
    messagingSenderId: '750270234587',
    projectId: 'nk-one-chat-app',
    storageBucket: 'nk-one-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.oneChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr1SsSrPH6ysXQb7NZLvz1iafMrGv5_e8',
    appId: '1:750270234587:web:55885d1cae2cc43b72f1fe',
    messagingSenderId: '750270234587',
    projectId: 'nk-one-chat-app',
    authDomain: 'nk-one-chat-app.firebaseapp.com',
    storageBucket: 'nk-one-chat-app.firebasestorage.app',
  );

}